# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 24345ccd8daeb20873a28de0398fa7010702be586f8f8d4b02e68d913451963c96c912345d1d866fcd07465855913b55c62c66613433d695a2bd308673412272

test:
  secret_key_base: 9045a0616b92a0887d3a80da1ab2d7f3a098d3c1788189901f099d0ad7ba6a78c0dcfb41a219cd65f594833fcf6eb0bf46ac7f75d7ea9a14ced45a2bcda262f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
